<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.5.3.1 setup script
 * Date: Mon, 04 Jul 2016 22:38:01 -0400
 */

/* Servers configuration */
$i = 0;

/* Server: MySQL [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'MySQL';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3307;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'b4v0e1jj';

/* End of servers configuration */

$cfg['blowfish_secret'] = '577b1c833cb377.08307066';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['GZipDump'] = false;
$cfg['BZipDump'] = false;
?>